fixed NoSuchMethodError: The getter 'length' was called on null, caused by calling decode on null if app has no saved lists (SP returns null in that case)